# Generated by Django 3.2 on 2021-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210615_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms_of_use',
            field=models.BooleanField(default=True),
        ),
    ]
