# Generated by Django 3.2 on 2021-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
