# Generated by Django 3.2 on 2021-07-28 13:03

from django.db import migrations


def set_email_verified(apps, schema_editor):
    EmailAddress = apps.get_model('account', 'EmailAddress')
    for email in EmailAddress.objects.filter(code__isnull=True):
        email.verified = True
        email.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_emailaddress_verified'),
    ]

    operations = [
        migrations.RunPython(set_email_verified),
    ]
