# Generated by Django 3.2.5 on 2021-08-16 12:35

from django.conf import settings
from django.db import migrations, models
from django.db.utils import OperationalError, ProgrammingError
import django.db.models.deletion


def copy_from_api_subscription(apps, schema_editor):
    """
    Copy access events from the old table to the new one.
    Delete the olds
    """
    try:
        # get models
        ApiSubscriptionAccessEvent = apps.get_model('api_subscription', 'AccessEvent')
        AccountAccessEvent = apps.get_model('account', 'AccessEvent')

        for api_subscription_accessevent in ApiSubscriptionAccessEvent.objects.all():
            # create entry copy in new app
            account_accessevent = AccountAccessEvent.objects.create(
                pk=api_subscription_accessevent.pk,
                ip_address=api_subscription_accessevent.ip_address,
                access_type=api_subscription_accessevent.access_type,
                query=api_subscription_accessevent.query,
                user=api_subscription_accessevent.user,
            )
            # auto_now fields are special, we have to update them this way
            AccountAccessEvent.objects.filter(pk=account_accessevent.pk).update(
                created_at=api_subscription_accessevent.created_at,
                modified_at=api_subscription_accessevent.modified_at,
            )
            # delete the old object so the code fail if it still uses it (which would be a bug)
            api_subscription_accessevent.delete()

    except (LookupError, OperationalError, ProgrammingError):
        # An app may be deleted, so fail is ok. It just means we don't need to copy data
        return


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210728_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('access_type', models.CharField(choices=[('rent_analyzer_search', 'Rent Analyzer Search'), ('rent_analyzer_report', 'Rent Analyzer Report'), ('property_report', 'Property Report')], max_length=100)),
                ('query', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(copy_from_api_subscription),
    ]
