# Generated by Django 3.2.5 on 2021-08-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_accessevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproperty',
            options={'verbose_name': 'favorite property', 'verbose_name_plural': 'favorite properties'},
        ),
    ]
