# Generated by Django 3.2.5 on 2021-08-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210819_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
