# Generated by Django 3.2.5 on 2021-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_customuser_is_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproperty',
            name='photo1',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
