# Generated by Django 3.2.5 on 2021-10-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_favoriteproperty_photo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='paid_plan',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='paid_status',
        ),
    ]
