# Generated by Django 3.2.5 on 2021-12-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211020_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='access_type',
            field=models.CharField(choices=[('rent_analyzer_search', 'Rent Analyzer Search'), ('rent_analyzer_report', 'Rent Analyzer Report'), ('property_report', 'Property Report'), ('rent_estimator_analytics', 'Rent Estimator Analytics')], max_length=100),
        ),
    ]
