# Generated by Django 3.2.10 on 2022-01-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_accessevent_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproperty',
            name='predicted_rent',
            field=models.FloatField(null=True, blank=True),
        ),
    ]
