# Generated by Django 3.2.10 on 2022-01-18 14:20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_add_some_fields_to_cache_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproperty',
            name='prop_class',
            field=models.CharField(choices=[('invest', 'Invest'), ('buy', 'Buy'), ('rent', 'Rent')], default='invest', max_length=20, null=True),
        ),
    ]
