# Generated by Django 3.2.10 on 2022-03-28 13:43

from django.db import migrations


def drop_duplicates(apps, db_editor):
    try:
        FavoriteProperty = apps.get_model('account', 'FavoriteProperty')
        CustomUser = apps.get_model('account', 'CustomUser')
        for user in CustomUser.objects.all():
            for prop_class in ('buy', 'invest'):
                duplicates = FavoriteProperty.objects.filter(prop_class=prop_class, user=user)
                for prop_id in duplicates.values_list('prop_id', flat=True).distinct():
                    FavoriteProperty.objects.filter(pk__in=FavoriteProperty.objects.filter(
                        prop_id=prop_id, prop_class=prop_class).values_list('id', flat=True)[1:]).delete()

    except Exception as e:
        print('something goes wrong, but it\'s ok  if migration is old', e)



class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_customuser_phone'),
    ]

    operations = [
        migrations.RunPython(drop_duplicates),
    ]
