# Generated by Django 4.0 on 2022-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_delete_duplicat'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproperty',
            name='furnished',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='laundry',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='parking',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='pet_friendly',
            field=models.BooleanField(null=True, blank=True),
        ),
    ]
