# Generated by Django 4.0 on 2022-05-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_favoriteproperty_furnished_favoriteproperty_laundry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproperty',
            name='prop_id',
            field=models.CharField(max_length=21),
        ),
    ]
