# Generated by Django 4.0.4 on 2022-07-19 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_favoriteproperty_prop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
