# Generated by Django 4.0.6 on 2022-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_emailsettings_favorites_good_deals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='alerts_city',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='alerts_property',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='comm_monthly_newsletters',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='comm_product_updates',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='comm_promotions',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='comm_tips_blogs',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='market_reports_and_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='partner_offers_and_deals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='tips_and_guides',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='tool_updates',
            field=models.BooleanField(default=True),
        ),
    ]
