# Generated by Django 4.0.6 on 2022-11-03 17:18

from django.db import migrations, models
import django.db.models.deletion


def create_good_deal_settings(apps, schema_editor):
    User = apps.get_model('account.CustomUser')
    GoodDealSettings = apps.get_model('account.GoodDealSettings')
    for user in User.objects.all():
        if not GoodDealSettings.objects.filter(user=user):
            GoodDealSettings.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_track_new_email_settings'),
        ('api_property', '0014_propcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDealSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('rent_min_price', models.IntegerField(default=200, blank=True, null=True)),
                ('rent_max_price', models.IntegerField(default=20_000, blank=True, null=True)),
                ('buy_min_price', models.IntegerField(default=10_000, blank=True, null=True)),
                ('buy_max_price', models.IntegerField(default=10_000_000, blank=True, null=True)),
                ('invest_min_price', models.IntegerField(default=10_000, blank=True, null=True)),
                ('invest_max_price', models.IntegerField(default=10_000_000, blank=True, null=True)),
                ('rent_enabled', models.BooleanField(default=False)),
                ('buy_enabled', models.BooleanField(default=False)),
                ('invest_enabled', models.BooleanField(default=False)),
                ('prop_type', models.CharField(blank=True, choices=[('condo-apt', 'Condo'), ('house-duplex', 'Single Family'), ('townhouse', 'Townhome')], max_length=20, null=True)),
                ('beds_min', models.IntegerField(blank=True, null=True)),
                ('baths_min', models.IntegerField(blank=True, null=True)),
                ('cities', models.ManyToManyField(to='api_property.propcity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CustomUser')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'good deal settingses',
            },
        ),
        migrations.RunPython(create_good_deal_settings)
    ]
