# Generated by Django 4.0.6 on 2022-11-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_gooddealsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='favorites_match_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='properties_you_may_like',
            field=models.BooleanField(default=True),
        ),
    ]
