# Generated by Django 4.0.6 on 2022-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_turn_on_favorite_email_settings_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_login',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_login',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
