# Generated by Django 4.0.6 on 2023-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_customuser_facebook_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='facebook_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_login',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fb_user_id',
            field=models.CharField(blank=True, default='', max_length=31),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_user_id',
            field=models.CharField(blank=True, default='', max_length=31),
        ),
    ]
