# Generated by Django 3.2.4 on 2021-06-11 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('request', models.TextField(max_length=4096)),
                ('prop_id', models.CharField(max_length=20)),
                ('prop_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('Stripe', 'Stripe')], max_length=100)),
                ('plan', models.CharField(choices=[('Premium', 'Premium')], max_length=100)),
                ('period', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], max_length=100)),
                ('session_id', models.CharField(default='', max_length=100)),
                ('subscription_id', models.CharField(default='', max_length=100)),
                ('created_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('paid_by', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing')], max_length=100, null=True)),
                ('user_cancel_reason', models.TextField(blank=True, default='', max_length=2048, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('step1', models.TextField(max_length=2048)),
                ('step2', models.TextField(max_length=2048)),
                ('step3', models.TextField(max_length=2048)),
                ('step4', models.TextField(max_length=2048)),
                ('step5', models.TextField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
