# Generated by Django 3.2.5 on 2021-07-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210615_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_time',
        ),
    ]
