# Generated by Django 3.2.5 on 2021-08-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_quiz_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
