# Generated by Django 3.2.5 on 2021-08-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_delete_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactAgent',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
