CREATE TABLE prop_cache (
    "prop_id" varchar(21) PRIMARY KEY,
    "real_prop_id" varchar(21),
    "state_id" varchar(2),
    "zip" varchar(5),
    "status" varchar(20),
    "badges" varchar(100),
    "list_date" timestamp,
    "update_date" timestamp,
    "params" jsonb,
    "data" jsonb,
    "address" jsonb,
    "features" jsonb,
    "schools" jsonb,
    "tax_history" jsonb,
    "prop_history" jsonb,
    "public_records" jsonb,
    "to_delete" boolean,
    "is_test" boolean,
    "mls_events" jsonb,
    "price_change_events" jsonb,
    "last_price_change" jsonb,
    "prop_class" varchar(16),
    "similar_str" varchar(80),
    "building_id" varchar(32)
);
