CREATE TABLE IF NOT EXISTS seo_links_test (
    id integer NOT NULL,
    section character varying(16) DEFAULT '' NOT NULL,
    state_id character varying(2) DEFAULT '' NOT NULL,
    county character varying(255) DEFAULT '' NOT NULL,
    city character varying(255) DEFAULT '' NOT NULL,
    zip character varying(255) DEFAULT '' NOT NULL,
    prop_type character varying(32) DEFAULT '' NOT NULL,
    facet character varying(64) DEFAULT '' NOT NULL,
    prop_count integer DEFAULT 0 NOT NULL,
    cat_popular_cities text,
    cat_popular_counties text,
    cat_popular_zips text,
    cat_nearby_cities text,
    cat_nearby_counties text,
    cat_nearby_zips text,
    updated_at timestamp without time zone DEFAULT now(),
    county_original character varying(255) DEFAULT '' NOT NULL,
    city_original character varying(255) DEFAULT '' NOT NULL,
    in_google_index boolean DEFAULT false NOT NULL,
    indexable boolean DEFAULT true NOT NULL,
    google_index_ts timestamp without time zone,
    near_me_indexable boolean DEFAULT false NOT NULL
);
