# Generated by Django 3.2.5 on 2021-08-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210615_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'blog category', 'verbose_name_plural': 'blog categories'},
        ),
    ]
