# Generated by Django 4.0.6 on 2022-08-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_auto_20220818_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViewCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('article_id', models.IntegerField(unique=True)),
                ('count', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
