# Generated by Django 4.0.6 on 2022-08-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_create_articleviewcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleviewcounter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
