# Generated by Django 3.2.4 on 2021-06-21 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import common.encoders
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('rent_analyzer', 'Rent Analyzer'), ('property', 'Property')], max_length=100)),
                ('report_file', models.FileField(upload_to=reports.models._generate_upload_path)),
                ('query', models.JSONField()),
                ('data', models.JSONField(encoder=common.encoders.DjangoNumpyJSONEncoder)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
