# Generated by Django 3.2.5 on 2021-07-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='list_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
