# Generated by Django 3.2.5 on 2021-08-18 14:16

from django.db import migrations, models
from django.db.utils import OperationalError, ProgrammingError


def copy_from_common(apps, schema_editor):
    """
    Copy contact agents from the old table to the new one.
    Delete the olds
    """
    try:
        # get models
        CommonContactAgent = apps.get_model('common', 'ContactAgent')
        ApiPropertyContactAgent = apps.get_model('api_property', 'ContactAgent')

        for common_contactagent in CommonContactAgent.objects.all():
            # create entry copy in new app
            apiproperty_contactagent = ApiPropertyContactAgent.objects.create(
                pk=common_contactagent.pk,
                full_name=common_contactagent.full_name,
                email=common_contactagent.email,
                phone=common_contactagent.phone,
                request=common_contactagent.request,
                prop_id=common_contactagent.prop_id,
                prop_address=common_contactagent.prop_address,
            )
            # auto_now fields are special, we have to update them this way
            ApiPropertyContactAgent.objects.filter(pk=apiproperty_contactagent.pk).update(
                created_at=common_contactagent.created_at,
                modified_at=common_contactagent.modified_at,
            )
            # delete the old object so the code fail if it still uses it (which would be a bug)
            common_contactagent.delete()

    except (LookupError, OperationalError, ProgrammingError):
        # An app may be deleted, so fail is ok. It just means we don't need to copy data
        return


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_alter_quiz_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('request', models.TextField(max_length=4096)),
                ('prop_id', models.CharField(max_length=20)),
                ('prop_address', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(copy_from_common),
    ]
