# Generated by Django 3.2 on 2022-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactagent',
            name='prop_id',
            field=models.CharField(max_length=21),
        ),
    ]
