# Generated by Django 3.2 on 2022-06-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0002_alter_contactagent_prop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactagent',
            name='site_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
