# Generated by Django 4.0.4 on 2022-07-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0003_contactagent_site_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactagent',
            old_name='site_url',
            new_name='url',
        ),
    ]
