# Generated by Django 4.0.4 on 2022-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0004_rename_site_url_contactagent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactagent',
            name='order_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
