# Generated by Django 4.0.6 on 2022-07-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0005_contactagent_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactagent',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contactagent',
            name='prop_class',
            field=models.CharField(choices=[('invest', 'Invest'), ('buy', 'Buy'), ('rent', 'Rent')], max_length=8, null=True),
        ),
    ]
