# Generated by Django 4.0.4 on 2022-07-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0007_sheets_new_cols'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sent_to_us', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('prop_id', models.CharField(max_length=21)),
                ('prop_class', models.CharField(max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'alert similar',
                'verbose_name_plural': 'alerts similar',
            },
        ),
    ]
