# Generated by Django 4.0.4 on 2022-07-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0008_alertsimilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsimilar',
            name='prop_class',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
