# Generated by Django 4.0.4 on 2022-08-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0009_alter_alertsimilar_prop_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactagent',
            name='move_in_date',
            field=models.DateField(null=True),
        ),
    ]
