# Generated by Django 4.0.6 on 2022-10-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency('account.CustomUser'),
        ('api_property', '0010_contactagent_move_in_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarPropertyNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('prop_id', models.CharField(max_length=21)),
                ('prop_class', models.CharField(choices=[('invest', 'Invest'), ('buy', 'Buy'), ('rent', 'Rent')], max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_props', to='account.CustomUser')),
            ],
            options={
                'verbose_name': 'Similar Property Notification',
            },
        ),
    ]
