# Generated by Django 4.0.6 on 2022-10-31 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_property', '0011_similarpropertynotificationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNotified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('prop_id', models.CharField(max_length=21)),
                ('prop_class', models.CharField(choices=[('invest', 'Invest'), ('buy', 'Buy'), ('rent', 'Rent')], max_length=6)),
                ('topic', models.CharField(choices=[('similar', 'Similar Property'), ('good_deal', 'Good Deal'), ('prop_history', 'Property History Update'), ('favorite_history', 'Favorite Property History Update'), ('favorite_similar', 'Favorite Similar Property')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props_notified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
