# Generated by Django 4.0.6 on 2022-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0013_propertyupdatemodel_gooddealsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=32)),
                ('county', models.CharField(max_length=32)),
                ('state_id', models.CharField(max_length=3)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
