# Generated by Django 4.0.6 on 2022-11-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0014_propcity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodDealsModel',
        ),
    ]
