# Generated by Django 4.0.6 on 2022-11-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0016_propertyupdatemodel_last_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyupdatemodel',
            old_name='last_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='propertyupdatemodel',
            old_name='last_status',
            new_name='status',
        ),
    ]
