# Generated by Django 4.0.6 on 2023-01-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0018_contactagent_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertSimilar',
        ),
    ]
