# Generated by Django 4.0.6 on 2023-02-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0019_delete_alertsimilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('photos', models.JSONField()),
            ],
            options={
                'db_table': 'buildings',
                'managed': False,
            },
        ),
    ]
