# Generated by Django 4.0.6 on 2023-11-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_property', '0020_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': True},
        ),
    ]
