WP_POST_1 = {'_links': {'about': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/types/post'}],
    'author': [{'embeddable': True, 'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/users/1'}],
    'collection': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/posts'}],
    'curies': [{'href': 'https://api.w.org/{rel}', 'name': 'wp', 'templated': True}],
    'predecessor-version': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/posts/1/revisions/6', 'id': 6}],
    'replies': [{'embeddable': True, 'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/comments?post=1'}],
    'self': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/posts/1'}],
    'version-history': [{'count': 1, 'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/posts/1/revisions'}],
    'wp:attachment': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/media?parent=1'}],
    'wp:term': [{'embeddable': True,
                 'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/categories?post=1',
                 'taxonomy': 'category'},
                {'embeddable': True,
                 'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/tags?post=1',
                 'taxonomy': 'post_tag'}]},
    'author': 1,
    'categories': [1],
    'comment_status': 'open',
    'content': {'protected': False,
                'rendered': '\n<p>Welcome to WordPress. This is your first post. '
                            'Edit or delete it, then start writing!</p>\n'},
    'date': '2022-08-18T08:44:01',
    'date_gmt': '2022-08-18T08:44:01',
    'excerpt': {'protected': False,
                'rendered': '<p>Welcome to WordPress. This is your first post. '
                            'Edit or delete it, then start writing!</p>\n'},
    'featured_media': 7,
    'format': 'standard',
    'guid': {'rendered': 'https://rsprjblog.ofirio.com/?p=1'},
    'id': 1,
    'link': 'https://rsprjblog.ofirio.com/hello-world/',
    'meta': [],
    'modified': '2022-08-18T08:44:01',
    'modified_gmt': '2022-08-18T08:44:01',
    'ping_status': 'open',
    'slug': 'hello-world',
    'status': 'publish',
    'sticky': False,
    'tags': [],
    'template': '',
    'title': {'rendered': 'Hello world!'},
    'type': 'post',
    'yoast_head_json': {'title': 'Test arcticle1 - Ofirio Test Blog TEST dflgsdf',
                        'description': '123123 test'},
    }


WP_POST_3 = {'author': 1,
    'categories': [1],
    'comment_status': 'open',
    'content': {'protected': False,
                'rendered': (
                    '\n<p>Awesome houses</p>\n\n\n\n    {{RELATED-POSTS}}eyJwb3N0X2lkcyI6IFsxXX0='
                    '{{/RELATED-POSTS}}\n{{RECOMMENDATIONS}}eyJ1cmwiOiIvYnV5L2NhL2JyaXNiYW5lIiwgI'
                    'mNvdW50IjoiOSIsICJ0aXRsZSI6IiIsInNlby10YWciOiJzcGFuIn0={{/RECOMMENDATIONS}} '
                ),
               },
    'date': '2022-09-01T17:20:18',
    'date_gmt': '2022-09-01T17:20:18',
    'excerpt': {'protected': False, 'rendered': '<p>Awesome houses</p>\n'},
    'featured_media': 0,
    'format': 'standard',
    'guid': {'rendered': 'https://rsprjblog.ofirio.com/?p=3'},
    'id': 3,
    'link': 'https://rsprjblog.ofirio.com/houses/',
    'meta': [],
    'modified': '2022-09-01T17:20:19',
    'modified_gmt': '2022-09-01T17:20:19',
    'ping_status': 'open',
    'slug': 'houses',
    'status': 'publish',
    'sticky': False,
    'tags': [],
    'template': '',
    'title': {'rendered': 'houses'},
    'type': 'post',
    'yoast_head_json': {'article_modified_time': '2022-09-01T17:20:19+00:00',
                        'article_published_time': '2022-09-01T17:20:18+00:00',
                        'author': 'rsprj_blog_admin',
                        'og_description': 'Awesome houses',
                        'og_locale': 'en_US',
                        'og_site_name': 'Ofirio Blog',
                        'og_title': 'houses - Ofirio Blog',
                        'og_type': 'article',
                        'og_url': 'https://rsprjblog.ofirio.com/houses/',
                        'robots': {'follow': 'follow',
                                'index': 'noindex',
                                'max-image-preview': 'max-image-preview:large',
                                'max-snippet': 'max-snippet:-1',
                                'max-video-preview': 'max-video-preview:-1'},
                        'title': 'houses - Ofirio Blog',
                        'twitter_card': 'summary_large_image',
                        'twitter_misc': {'Est. reading time': '1 minute',
                                         'Written by': 'rsprj_blog_admin'}}}


WP_USER_1 = {'_links': {'collection': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/users'}],
    'self': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/users/1'}]},
    'avatar_urls': {'24': 'https://secure.gravatar.com/avatar/6f248b054e3fe3d3c9fe234af41785fb?s=24&d=mm&r=g',
                    '48': 'https://secure.gravatar.com/avatar/6f248b054e3fe3d3c9fe234af41785fb?s=48&d=mm&r=g',
                    '96': 'https://secure.gravatar.com/avatar/6f248b054e3fe3d3c9fe234af41785fb?s=96&d=mm&r=g'},
    'description': 'Biographical Info',
    'id': 1,
    'link': 'https://rsprjblog.ofirio.com/author/ofirio_author/',
    'meta': [],
    'name': 'ofirio_author',
    'slug': 'ofirio_author',
    'url': 'https://rsprjblog.ofirio.com',
    'yoast_head_json': {'title': 'ofirio_author',
                        'description': 'Biographical Info'},
}


WP_CATEGORY_1 = {'_links': {'about': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/taxonomies/category'}],
            'collection': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/categories'}],
            'curies': [{'href': 'https://api.w.org/{rel}',
                        'name': 'wp',
                        'templated': True}],
            'self': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/categories/1'}],
            'wp:post_type': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/posts?categories=1'}]},
    'count': 1,
    'description': '',
    'id': 1,
    'link': 'https://rsprjblog.ofirio.com/category/uncategorized/',
    'meta': [],
    'name': 'Uncategorized',
    'parent': 0,
    'slug': 'uncategorized',
    'taxonomy': 'category',
    'yoast_head_json': {'title': 'Uncategorized',
                        'description': ''},
    }


# simulate that there is no category 2


# empty category, without posts
WP_CATEGORY_3 = {'_links': {'about': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/taxonomies/category'}],
            'collection': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/categories'}],
            'curies': [{'href': 'https://api.w.org/{rel}',
                        'name': 'wp',
                        'templated': True}],
            'self': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/categories/3'}],
            'wp:post_type': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/posts?categories=3'}]},
    'count': 0,
    'description': '',
    'id': 3,
    'link': 'https://rsprjblog.ofirio.com/category/cat3/',
    'meta': [],
    'name': 'Cat3',
    'parent': 0,
    'slug': 'cat3',
    'taxonomy': 'category',
    'yoast_head_json': {'title': 'Cat3',
                        'description': ''},
}


WP_MEDIA_7 = {'_links': {'about': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/types/attachment'}],
            'author': [{'embeddable': True,
                        'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/users/1'}],
            'collection': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/media'}],
            'replies': [{'embeddable': True,
                         'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/comments?post=7'}],
            'self': [{'href': 'https://rsprjblog.ofirio.com/wp-json/wp/v2/media/7'}]},
    'alt_text': '',
    'author': 1,
    'caption': {'rendered': ''},
    'comment_status': 'open',
    'date': '2022-08-18T15:00:37',
    'date_gmt': '2022-08-18T15:00:37',
    'description': {'rendered': '<p class="attachment"><a '
                             "href='https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties.png'><img "
                             'width="300" height="300" '
                             'src="https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties-300x300.png" '
                             'class="attachment-medium size-medium" alt="" '
                             'loading="lazy" '
                             'srcset="https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties-300x300.png '
                             '300w, '
                             'https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties-150x150.png '
                             '150w, '
                             'https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties.png '
                             '512w" sizes="(max-width: 300px) 100vw, 300px" '
                             '/></a></p>\n'},
    'guid': {'rendered': 'https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties.png'},
    'id': 7,
    'link': 'https://rsprjblog.ofirio.com/author-of-articles-about-real-estate-properties/',
    'media_details': {'file': '2022/08/author-of-articles-about-real-estate-properties.png',
                   'filesize': 246865,
                   'height': 512,
                   'image_meta': {'aperture': '0',
                                  'camera': '',
                                  'caption': '',
                                  'copyright': '',
                                  'created_timestamp': '0',
                                  'credit': '',
                                  'focal_length': '0',
                                  'iso': '0',
                                  'keywords': [],
                                  'orientation': '0',
                                  'shutter_speed': '0',
                                  'title': ''},
                   'sizes': {'full': {'file': 'author-of-articles-about-real-estate-properties.png',
                                      'height': 512,
                                      'mime_type': 'image/png',
                                      'source_url': 'https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties.png',
                                      'width': 512},
                             'medium': {'file': 'author-of-articles-about-real-estate-properties-300x300.png',
                                        'filesize': 120600,
                                        'height': 300,
                                        'mime_type': 'image/png',
                                        'source_url': 'https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties-300x300.png',
                                        'width': 300},
                             'thumbnail': {'file': 'author-of-articles-about-real-estate-properties-150x150.png',
                                           'filesize': 39382,
                                           'height': 150,
                                           'mime_type': 'image/png',
                                           'source_url': 'https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties-150x150.png',
                                           'width': 150}},
                   'width': 512},
    'media_type': 'image',
    'meta': [],
    'mime_type': 'image/png',
    'modified': '2022-08-18T15:00:37',
    'modified_gmt': '2022-08-18T15:00:37',
    'ping_status': 'closed',
    'post': None,
    'slug': 'author-of-articles-about-real-estate-properties',
    'source_url': 'https://rsprjblog.ofirio.com/wp-content/uploads/2022/08/author-of-articles-about-real-estate-properties.png',
    'status': 'inherit',
    'template': '',
    'title': {'rendered': 'author of articles about real estate properties'},
    'type': 'attachment'}
