# Generated by Django 3.2 on 2022-10-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpinTextCache',
            fields=[
                ('text_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('variables', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spin_text_cache',
                'managed': False,
            },
        ),
    ]
