# Generated by Django 4.0.6 on 2023-03-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_create_text_spin_cache_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceStat',
            fields=[
                ('place', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_stat',
                'managed': False,
            },
        ),
    ]
