# Generated by Django 4.0.6 on 2023-11-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_placestat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placestat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='spintextcache',
            options={'managed': True},
        ),
    ]
